VertaAI/modeldb-client

verta/setup.py, verta/verta/modeldbclient.py
Pickling is now done within the log_model function
=> Adding pickling to log_model

workflows/demos/functions.ipynb, workflows/demos/parallel.ipynb, workflows/demos/pytorch.ipynb, workflows/demos/sklearn.ipynb, workflows/demos/tensorflow.ipynb
Added a markdown link to open existing demos in colab with a simple pip command to install verta before running.
=> Demos now easily accessible to play on Google Colab

verta/verta/_utils.py, verta/verta/modeldbclient.py
=> Add flat key validation

verta/verta/modeldbclient.py
=> Ignore duplicates when adding ExptRunses

verta/verta/modeldbclient.py
Fixes #38. Main bug fix commit is 24027433e72d7c0afb3a62ceeca15481f9c5d2a4.
=> Attempt to create before getting

verta/verta/modeldbclient.py
=> 806: Return bytestream instead of bytestring

verta/verta/_demo_utils.py
To be used as follows:
```back
export VERTA_EMAIL=. . .
export VERTA_DEV_KEY=. . .
```
```python
from verta._demo_utils import ModelDeployment
model = ModelDeployment("demo1.verta.ai", model_id)
print(model.predict(x))
```
=> 846: Create _demo_utils module to perform clientside predictions

workflows/demos/sklearn.ipynb, workflows/demos/tensorflow.ipynb, workflows/demos/xgboost.ipynb
No deployment artifacts yet! Also no datasets yet because I'm still figuring that out
- [sklearn.ipynb](https://github.com/convoliution/modeldb-client/blob/c8d3044a78fb8e573a71f8f11dc97fb90eeb0606/workflows/demos/sklearn.ipynb)
- [tensorflow.ipynb](https://github.com/convoliution/modeldb-client/blob/c8d3044a78fb8e573a71f8f11dc97fb90eeb0606/workflows/demos/tensorflow.ipynb)
- [xgboost.ipynb](https://github.com/convoliution/modeldb-client/blob/c8d3044a78fb8e573a71f8f11dc97fb90eeb0606/workflows/demos/xgboost.ipynb)
=> 830, 831, 832: Add client querying to demos

verta/setup.py, verta/verta/_artifact_utils.py
- add `cloudpickle` as a dependency, by request
=> 920: Support getting models with cloudpickle

verta/verta/_utils.py, verta/verta/client.py
- implement utilities for unraveling `repeated` `Message` fields into proper collections
- implement an actual informative `__repr__()` for `ExperimentRun`
=> 691: Implement descriptive expt_run.__repr__() 

verta/verta/_artifact_utils.py
=>  1063: Reset stream position on failed deserializations

verta/verta/client.py
Ideally, I would like for the monitoring service to support both DataFrames and CSVs, but this should be an acceptable measure for the time being.
This conversion behavior in `log_model_for_deployment()` should be clear to the user through the parameter name and the docstring.
=> 1061: Convert DataFrame into CSV in log_model_for_deployment()

verta/tests/test_entities.py
The back end cannot guarantee that ExperimentRuns (or anything, really) are always logged in the same order they were sent, so the tests should not expect it.
=> 1078: Use sets instead of lists for ExptRuns tests

verta/tests/test_artifacts.py, verta/verta/client.py
See [the associated ticket](https://vertaai.atlassian.net/browse/VR-866) for context.
=> 866: Expose separate functions for logging path-only "artifacts"

verta/verta/_utils.py, verta/verta/client.py
See [the associated ticket](https://vertaai.atlassian.net/browse/VR-1081) for context.
There is a lower-priority issue with this implementation. See that backlogged ticket [here](https://vertaai.atlassian.net/browse/VR-1106).
=> 1081: Add cloudpickle to requirements if it was used

verta/verta/_artifact_utils.py, verta/verta/client.py
=> 1117: Implement utility to check for exact version pins in a requirements.txt

verta/docs/reference/changelog.rst, verta/setup.py, workflows/examples-without-verta/notebooks/sklearn-census.ipynb
Some changes went straight into master. This PR brings them to the development branch.
=> Merge master to development

verta/verta/_utils.py, verta/verta/client.py
- implement utility function for REST calls
- implement `max_retries` parameter and attribute on `Client` that propagates down to `Project`, `Experiment`, `ExperimentRun`, and `ExperimentRuns`
We sometimes see 404s resulting from back end connection lapses, but it is _not_ a good idea to blindly retry on them because certain operations (namely GETs) can result in legitimate 404s. Thus for now, there are no retries on 404s.
=> Implement clientside request retries

verta/verta/_utils.py
The function first saves the notebook via the Jupyter javascript
interface and monitors it's done via the modification time. Once it's
finished, the function returns and the content can be read from disk.
=> Add util function to get notebook contents

verta/verta/client.py
- move `log_model_for_deployment()` to bottom of file so it's grouped with other deployment functions
- implement `log_modules_for_deployment()`
=> Enable Logging of Custom Modules

verta/verta/_utils.py
I seem to have accidentally closed #125
=> Implement internal utils for finding git info

verta/verta/_artifact_utils.py
=> Implement utility for getting filepath extension

verta/verta/_utils.py, verta/verta/client.py
=> Implement _utils::Configuration.use_git

verta/verta/_demo_utils.py
Dynamically fetch prediction endpoint URL.
=> Support Custom Deployment URL

verta/verta/client.py
To resolve
```
TypeError: super() argument 1 must be type, not classobj
```
=> Convert to new-style classes

workflows/examples/custom-modules/custom-modules.ipynb, workflows/examples/custom-modules/models/nets.py, workflows/examples/custom-modules/utils/data.py, workflows/examples/custom-modules/utils/preprocess.py
=> Add Custom Modules Example Notebook

verta/verta/__about__.py, verta/verta/__init__.py, verta/verta/_artifact_utils.py, verta/verta/_demo_utils.py, verta/verta/_utils.py, verta/verta/client.py, verta/verta/utils.py
=> VR-1860: Define source code encoding

verta/verta/_demo_utils.py
I implemented `DeployedModel::from_url()` to call the class constructor with a dummy value for `model_id`, then overwrite attributes.
In the last couple of months—since first implementing most of the Client—I've learned that a good object design to consider is that constructors ought to contain as little logic as possible, and instead should just assign attributes on `self`. "Alternative constructors" can be implemented as class methods
So here's the deal: this entire `DeployedModel` thing needs to be moved to a "public" module soon anyway, and my plan for that is to overhaul the implementation of `_demo_utils::DeployedModel` to be a thin wrapper for this new public one, for backwards compatibility for users. So any implementation faux pas we commit here are temporary (whatever that …
=> VR-1901: Implement DeployedModel::from_url()

verta/setup.py, verta/verta/client.py
- cleanly handle `pillow`, `google.cloud.bigquery`, and `boto3` optional imports
- remove dependency on `pytz`
=> VR-1672: Enable Optional DataVer Imports

verta/verta/client.py
The logic in this PR was copied over directly from `Project`. Even I have issues with how this logic is organized, but there's not much to do about it right now.
=> VR-1739: Enable fetching existing Dataset by name  

verta/verta/client.py
~This Client change requires a DeploymentService update (new Runs will not work with old DeploymentService, although old Runs _will_ work with new DeploymentService).~
We're good to go!
Corresponding DeploymentService PR: https://github.com/VertaAI/DeploymentService/pull/138
The current user directory has _always_ been inside the tree captured with `log_modules()`, because it takes the current directory into account.
=> VR-1706: Support for different current working directories for deployment

verta/verta/client.py
Some of our customers are using `run.log_dataset_path()`, so it needs to be supported in the coming release. Eventually, it will be superceded by:
```python
dataset = client.set_dataset(name, type="local")
dataset_version = dataset.create_version(path_to_file)
run.log_dataset_version(key, dataset_version)
```
- move `Client._log_dataset_path()` logic into `ExperimentRun.log_dataset_version()`
- raise `DeprecationWarning` in `ExperimentRun.log_dataset_path()`
- change `ExperimentRun.log_dataset_path()` to create a new `Dataset`, `DatasetVersion`, and log it
=> Ensure run.log_dataset_path() is still useable

verta/docs/reference/api/dataset.rst, verta/tests/README.md, verta/tests/conftest.py, verta/tests/test_datasets.py, verta/verta/_dataset.py, verta/verta/client.py
Adds to Verta Client:
- `get_dataset`
- `get_dataset_version`
- `find_datasets`
Adds tests for above.
=> add functions to retrieve datasets

verta/tests/test_datasets.py, verta/verta/client.py
Fix tag-based searches and update tests.
=> searching fix

verta/verta/_dataset.py
=> VR-2098: Accept object's key prefix instead of full key for S3DatasetVersion

verta/verta/_dataset.py, verta/verta/client.py
Tsk tsk, Michael, this isn't Rust
=> Properly return from run.get_dataset_version()

verta/verta/deployment.py
=> Add examples to DeployedModel docs

verta/verta/client.py, verta/verta/monitoring.py
=> VR-2315: Change log_model_for_deployment to upload `HistogramProcessor`s

verta/verta/monitoring.py
`reduce_states()` now explicitly mutates `state1` because all that `deepcopy`ing was totally unnecessary.
=> Flatten state into simple list of counts

verta/verta/monitoring.py
Most of `_BinaryHistogramProcessor`'s logic is moved into a new `_DiscreteHistogramProcessor`, which `_BinaryHistogramProcessor` now subclasses.
=> Implement discrete histogram processors

verta/verta/monitoring.py
I've been copy-and-pasting this logic between four different classes so it seems to be a good candidate for just being inherited.
Also, I changed the `RuntimeError` into a `TypeError`.
=> Create _get_feature_value method in superclass

verta/verta/monitoring.py
=> VR-2333: Implement GroundTruthHistogramProcessor

verta/tests/test_deployment.py, verta/tests/test_monitoring.py
- update and skip `log_model_for_deployment()` data test because it's only on a particular namespace right now
- add a couple of tests for the `monitoring` utilities I wrote, because I had them
=> Test stuff

verta/verta/client.py
#255 but onto development instead of the `custom_monitoring` branch
=> Add verta to uploaded requirements if not present

verta/docs/reference/api/experimentrun.rst, verta/verta/client.py
#257 but onto development instead of the `custom_monitoring` branch
=> Implement run.log_setup_script()

verta/verta/_artifact_utils.py, verta/verta/_utils.py, verta/verta/client.py, verta/verta/utils.py
Passing to `log_model_for_deployment()` ZIPs and uploads SavedModel.
Pickling outside raises error.
=> Implement pickling utils.TFSavedModel

verta/verta/_utils.py, verta/verta/utils.py
The diff is all messed up because logic was moved from `__init__()` to `_map_tensors()`; see comments for changes.
This works locally.
=> Implement unpickling utils.TFSavedModel

verta/verta/deployment.py
`from_url()` fails without auth credentials, despite having a token.
`from_url()` succeeds without auth credentials.
=> VR-2496: Don't grab auth if using from_url()

workflows/demos/census-end-to-end-local-data-example.ipynb, workflows/demos/census-end-to-end-s3-example.ipynb, workflows/demos/census-end-to-end.ipynb
=> Clean up notebooks

verta/verta/client.py
Everywhere there is a `_get_url_for_artifact()`, handle `localhost`.
=> Handle NFS everywhere

verta/verta/_dataset.py, verta/verta/_utils.py
=> VR-2535: Mimic `datetime.timestamp()` for Python2 DataVersioning

verta/verta/client.py
Related Backend PR : https://github.com/VertaAI/verta-backend/pull/293
=> Fix for  backend to know scheme of host url

verta/verta/deployment.py
`502`s without JSON content are now retried 👍 
`502`s with JSON content still properly halt execution 👍
=> Retry on non-model 502s

verta/verta/deployment.py
=> Make prediction token optional

verta/verta/deployment.py
Tested by shutting down a model in the middle of predictions:
=> Add always_retry_404 parameter

verta/docs/reference/api/experimentrun.rst, verta/tests/test_deployment.py, verta/tests/test_entities.py, verta/verta/client.py
=> VR-2869: Enable fetching model artifacts clientside

verta/docs/reference/api/experimentrun.rst, verta/tests/test_deployment.py, verta/verta/_utils.py, verta/verta/client.py, verta/verta/deployment.py
- `run._get_deployment_status()`
- `run.deploy(path=None, token=None, no_token=False, wait=False)`
- `run.undeploy(wait=False)`
- test suite
=> Implement deployment functions on ExperimentRun

verta/tests/test_deployment.py, verta/verta/client.py
Pending changes in deployment pieces
=> VR-3008: Enable idempotent run.deploy() and run.undeploy()

verta/tests/test_deployment.py, verta/verta/client.py
Mirrors https://github.com/VertaAI/services/pull/257 but for the Client.
=> VR-2996: Unpack .tgz, .tar, and .tar.gz in fetch_artifacts()

verta/tests/test_datasets.py, verta/tests/test_log_code.py, verta/verta/client.py
=> VR-2972: Enable overwriting code and dataset versions

LICENSE
=> Add license to repo root

verta/tests/test_deployment.py
=> Update logic for custom modules tests

verta/verta/_dataset.py, verta/verta/_utils.py, verta/verta/client.py
- adds `workspace` parameter to `set_project()` and `set_dataset()`
- removes retries on `403`s
=> VR-3085, VR-3093: Add `workspace` parameter

verta/tests/test_integrations.py, verta/verta/_utils.py, verta/verta/integrations/keras/__init__.py, verta/verta/integrations/tensorflow/__init__.py
This basically only logs loss.
=> Add TensorFlow estimator hook

verta/docs/reference/api/integrations.rst, verta/requirements.txt, verta/tests/test_integrations.py, verta/verta/integrations/xgboost/__init__.py
Logs whatever `eval_metric`s the user passes into `xgb.train()`
=> VR-3146: Implement callback for XGBoost
