- verta/tests/test_workflow.py
- verta/verta/modeldbclient.py
This is **not** the final version of this function. Ideally, logging multiple hyperparameters would occur with one RPC (see [this issue](https://github.com/VertaAI/mdb-v2-backend/issues/38)), but this function should exist anyway (it'll make the user guide a bit cleaner).
> Implement logging multiple hyperparameters at once

- verta/tests/conftest.py
- verta/tests/test_entities.py
- verta/tests/test_workflow.py
- verta/verta/modeldbclient.py
Previously, the user would encounter an exception when attempting to set a description, tags, and/or attributes using `set_project()`, `set_experiment()`, and `set_experiment_run()` when an entity by the specified name already exists.
This is because `set_*()` shouldn't be used to write entity fields, and also because it seems a user would only do this if they assumed the entity didn't exist to begin with.
The exception has been changed to a warning so as to not halt execution of the workflow.
A flag to enable force-overwriting description, tags, and/or attributes through the `set_*()` function will be added in the future, once I actually implement functions to do those.
> Change set_* exceptions to warnings

- verta/requirements.txt
- verta/setup.py
- verta/tests/conftest.py
- verta/tests/test_entities.py
- verta/tests/test_protos.py
- verta/tests/test_workflow.py
- verta/verta/_compat.py
- verta/verta/_utils.py
- verta/verta/modeldbclient.py
An `__init__.py` *must be added* to the root dir of https://github.com/VertaAI/protos-modeldb-python/ because Python2 imports are not very smart. This has been made [an issue in the protos repo](https://github.com/VertaAI/protos-all-python/issues/2).
- enable installation with Python2.7
- add `six` as a dependency for:
- lazily iterating over dictionaries
- typechecking integers and strings
- importing `urlparse` module from std lib
- properly use `pathlib2` as `pathlib` backport
- remove keyword-only-arguments syntax
- create integration tests for `ExperimentRuns` methods
> Enable Python2 compatibility

- verta/setup.py
- verta/tests/test_workflow.py
- verta/verta/_utils.py
- verta/verta/modeldbclient.py
- remove `joblib` as a dependency, sticking with `pickle` for now instead
- remove the functions for getting all artifacts because:
- they're a hassle to implement properly
- fetching too many artifacts at once is performance-intensive
- [implement fn for converting an object into a bytestream](https://github.com/VertaAI/modeldb-client/compare/development...convoliution:s3?expand=1#diff-0320d7c96f347d1e665817a9d5a22f98R197)
- [implement fn for obtaining a presigned url for artifact store interaction](https://github.com/VertaAI/modeldb-client/compare/development...convoliution:s3?expand=1#diff-2e381627d68267b10f4c5063ed01f36eR930)
> 544, 668: Implement utils for artifact storage

- verta/verta/_utils.py
Important to note that `log_artifact()` doesn't exist yet.
> VR-608: Mention using artifact in error msg

- verta/setup.py
Pip's dependency resolver is a hot mess, and also user environments shouldn't be restricted arbitrarily.
> Free up dependency pins

- verta/verta/modeldbclient.py
It turns out I sneakily fixed 715 in another PR, so this change just adds to it by making the `KeyError` a bit more helpful (before, it just looked like an unhandled bug to the user).
> 715: Make sure `get_*`s actually use the right key

- verta/verta/_utils.py
- verta/verta/modeldbclient.py
- attempt to call `seek(0)` on file-like objects before casting into binary
- raise error on empty file-like objects because AWS otherwise returns an unhelpful 501
- raise error on empty strings as artifact paths because protobuf treats them as null values
> 720: Check for object emptiness

- verta/verta/modeldbclient.py
A user can't really directly do anything with a bytestring, but various ML libraries have functions that can handle file-like objects.
Therefore it's a bit more useful to return a file-like bytestream than the raw string itself.
> 806: Return bytestream instead of bytestring

- verta/verta/_utils.py
- verta/verta/utils.py
- move `dump()` and `load()` into new user-facing utils module
- this allows for future Verta-related external utilities
> 708: Create user-facing utils module

- verta/verta/modeldbclient.py
- workflows/demos/sklearn.ipynb
- return prediction response as `dict` instead of just printing it
- cache model api and prediction token on `ExperimentRun` instead of fetching on every prediction
> As requested

- verta/tests/conftest.py
- verta/verta/modeldbclient.py
- read `$MODELDB_EMAIL` and `$MODELDB_DEV_KEY` from the environment if they are not passed into `ModelDBClient` on init
> 721: Read client credentials from env vars

- verta/verta/modeldbclient.py
The entity's name is slightly more descriptive than the object's memory address.
If the entity's metadata also have clean string representations in the future, they could be added into these `__repr__`s.
> 685, 686, 687: Impl marginally more useful reprs

- verta/tests/conftest.py
- verta/tests/utils.py
- verta/verta/modeldbclient.py
- allow pytest to work without setting a port in the environment
- add a `_scheme` attribute to classes
- this is making REST calls more verbose, and highlights the need for a helper function to handle these
> 864: Use https with auth, http without

- verta/verta/_artifact_utils.py
- verta/verta/modeldbclient.py
- create an `_artifact_utils` module to organize serialization deserialization functions.
- need to migrate exiting functions from `modeldbclient.py`; this is Tech Debt VR-874
- implement function to deserialize models
- first tries to use `keras`'s `load_model()`, then unpickle, then just return the bytestream
- thanks to Python shenanigans, `verta` doesn't require installing `tensorflow` but will use the library if the user has it
- implement function to serialize models
- tries to call `model.save()`, then pickle, then failure
- `model` can be anything; `save(iostream)` is a fairly common interface
> Enable logging/getting Keras models

- verta/verta/_utils.py
- verta/verta/modeldbclient.py
- set `including_default_value_fields=True` in `_utils.proto_to_json()` to recover the defaults that protobuf hides
- implement `log_model_for_deployment()`
- logs artifacts using the keys that the dpeloyment service currently looks for
- the parameter `dataset` is optional; if it is not provided, then this function will look for an existing dataset artifact, download it to the client, then re-upload it using the deployment-specific key.
- I hope you cringed reading that as much as I cringed writing it
>  548: Implement log_model_for_deployment() 

- verta/tests/test_artifacts.py
- verta/tests/test_metadata.py
- verta/verta/modeldbclient.py
- in `log_{artifact, attribute, metric, hyperparameter}()`, check for HTTP 409 in the request response, and raise `ValueError`
- in `log_hyperparameters()`, check for any duplicate keys before doing any logging, because I've yet to integrate/test the atomic batch logging RPC
- rename `test_workflow.py` to `test_metadata.py` because I kept forgetting what it was called
- implement integration tests for duplicate key checks
The backend currently only checks duplicate keys for metrics and hyperparameters. Adding backend checks for artifacts and attributes is Tech Debt VR-898, and the integration tests for these items are commented out.
>  714: Implement duplicate key checks 

- verta/setup.py
- verta/tests/conftest.py
- verta/verta/__init__.py
- verta/verta/client.py
- workflows/demos/sklearn.ipynb
- workflows/demos/tensorflow.ipynb
- workflows/demos/xgboost.ipynb
- rename `modeldbclient.py` to `client.py`
- rename `ModelDBClient` to `Client`
- update docstrings to reflect renaming
- update test config to reflect renaming
@mvartakAtVerta Please make sure this change is reflected in the user guides; I've assigned Tutorials and Documentation VR-899 to you for this.
> 843: Rename ModelDBClient to Client

- verta/verta/_utils.py
- verta/verta/client.py
Hopefully this fixes the parallel name collision fiasco once and for all.
> 902: Use process ID in default name gen

- verta/verta/_utils.py
- ask the user to use `log_artifact()` for lists and dicts
- clarify error message when trying to cast unsupported type from proto to Python
- the Client only supports *logging* certain types, so *getting* an unsupported type shouldn't be possible for now
> Clean up Python-proto translation error catching

- verta/verta/_artifact_utils.py
- verta/verta/client.py
- create `serialize_model()` fn in `_artifact_utils` to use in both `log_model()` and `log_model_for_deployment()`
- `log_model_for_deployment()` can't call `log_model()`, because the latter has a key validity check, and by our own standards the deployment-specific keys are not actually valid
- so to properly bypass this check, I abstracted the model serialization logic to a helper function, which I would've done anyway
- juggle protobuf-python conversions in `log_model_for_deployment()`
- the json I get back in my request response is missing certain fields because in protobuf (and in Go), default values are equivalent to missing values
- to get these values back, I need to translate the json into a protobuf message and then back into a `dict`
- I actually tested …
> 907: Move model serialialization logic to _artifact_utils

- verta/verta/_artifact_utils.py
- verta/verta/_utils.py
- verta/verta/client.py
This is built on #75; you can view the true diff [here](https://github.com/convoliution/modeldb-client/compare/nyc...convoliution:veracruz).
- support `sklearn`, `tensorflow`, and `xgboost` models in `serialize_model()`
- if the function is passed a file handle, it will first attempt to deserialize that file to ascertain information about the model; if that doesn't work, it will just pass the file along
- if the function is passed an object, it will attempt to find information about its origin package (e.g. `sklearn`), and then serialize it
> 921: Determine model_type in log_model()

- verta/verta/_artifact_utils.py
- verta/verta/_utils.py
- verta/verta/client.py
This is built on #74; you can view the true diff [here](https://github.com/convoliution/modeldb-client/compare/alaska...convoliution:nyc).
- move `ensure_bytestream()` to `_artifact_utils` because it's an artifact utility
- enable use of `joblib` and `cloudpickle` in `ensure_bytestream()`
- essentially, the function will try dumping with `joblib`, then `cloudpickle`, then `pickle`, and return the serialized object along with a string describing which method succeeded
> 917: Support joblib and cloudpickle in artifact logging

- verta/verta/_artifact_utils.py
- verta/verta/_utils.py
- verta/verta/client.py
This is built on #76; you can view the true diff [here](https://github.com/convoliution/modeldb-client/compare/veracruz...convoliution:sacramento).
- implement `generate_model_api()` which takes data (as a CSV or a `pandas` `DataFrame`) and the serialization method and model type from `serialize_model()`
> 916: Implement generate_model_api

- verta/verta/_artifact_utils.py
- verta/verta/_utils.py
- verta/verta/client.py
- workflows/demos/sklearn.ipynb
- workflows/demos/tensorflow.ipynb
- workflows/demos/xgboost.ipynb
This is built on #77; you can view the true diff [here](https://github.com/convoliution/modeldb-client/compare/sacramento...VertaAI:notebooks).
- create and log `pandas` `DataFrames`
- uncomment `log_model_for_deployment()`
> 827, 828: Update notebooks with full artifact logging

- verta/verta/_utils.py
- verta/verta/client.py
- import `datetime` instead of `time` in _utils.py
- optionally import `pandas` in _utils.py
- implement `unravel_observation()` (singular), which lightly converts an `Observation` protobuf message into a Python tuple
- change `unravel_observations()` (plural) to use `unravel_observation()` (singular)
- change `generate_default_name()` to use the `datetime` module instead of `time`, to keep the number of imports low
- implement `timestamp_to_ms()`, which ensures that a numerical Unix timestamp is with millisecond precision (13 integer digits)
- implement `ensure_timestamp()`, which converts a string datetime representation (e.g. "Oct 30, 2017") into a Unix timestamp with millisecond precision, and also converts already-numerical timestamps to millisecond precision
- implement …
> 569: Associate timestamps with observations

- verta/tests/test_metadata.py
- verta/verta/client.py
`TestTags::test_duplicates()` current fails, but the test itself checks for intended behavior (silently ignore duplicate logged tags). Its success is blocked on backend changes by @ravishetye, but I do not believe that should block this PR.
> 554: Implement logging/getting tags on ExperimentRuns

- README.md
- verta/docs/guides/guides.rst
- verta/docs/guides/workflow.rst
- verta/tests/test_metadata.py
- verta/verta/client.py
- workflows/demos/census-end-to-end.ipynb
- workflows/examples/sklearn.ipynb
- workflows/examples/tensorflow.ipynb
- workflows/examples/xgboost.ipynb
In #87, I removed the ability to pass a `dict` into batch logging functions  
(e.g. `log_metrics(metrics_dict)`)  
and instead only supported dictionary unpacking  
(e.g. `log_metrics(**metrics_dict)`).
This morning, I realized that this is one of the worst ideas I've ever had, because this means that any future arguments we may add to these functions will potentially have collisions with metric keys.
Basically, if we added a parameter to `log_metrics()` called `lowercase` or something, the user would be unable to use this function to log a metric with the name `"lowercase"`. It's highly unlikely to come up but if it does, it will be a hassle to debug and fix, so we might as well reduce the chance to zero.
> Change batch logging functions to take a dict instead of kwargs

- verta/tests/test_artifacts.py
- verta/verta/_utils.py
- verta/verta/client.py
- remove a list-unpacked argument from a test function because Python 2 doesn't support that syntax
- implement `to_timestamp()`, because Python2 doesn't have `datetime::datetime.timestamp()`
- use `seek()` then `read()`, because Python 2's `StringIO` doesn't implement `getbuffer()`
- read `path_only` on artifact gets, because Python 2 doesn't have a bytestring type, and therefore "bytestrings" were being interpreted as paths and were not being deserialized for the user.
> Re-establish Py2 compatibility

- verta/verta/_artifact_utils.py
- verta/verta/client.py
Verifies that all dependencies listed in a requirements-file-format file-like object have an exact version pin, i.e. `==` and not e.g. `>=`.
This is of practical importance for reproducible/reliable deployment. The onus is on the user to make sure they know what Python environment is necessary to successfully build their model.
> 1117: Implement utility to check for exact version pins in a requirements.txt

- verta/verta/client.py
- workflows/demos/census-end-to-end.ipynb
- workflows/examples/sklearn.ipynb
- workflows/examples/tensorflow.ipynb
- workflows/examples/xgboost.ipynb
- basically just switch the positions of the dataset and the model API in `log_model_for_deployment()`'s parameters
This is a breaking change, though minor. The order of `log_model_for_deployment()`'s parameters is now different. Once this PR is merged—along with a near-future PR for generating the model API—examples and documentation have to be updated to reflect this and the use of the model API generation utility.
> 1116: Make dataset_df an optional parameter in log_model_for_deployment()

- verta/verta/_utils.py
- verta/verta/client.py
- workflows/demos/census-end-to-end.ipynb
- workflows/examples/sklearn.ipynb
- workflows/examples/tensorflow.ipynb
- workflows/examples/xgboost.ipynb
- remove `verta._utils.get_env_dependencies` until further notice
- use `cloudpickle.__version__` to obtain its version number instead of `pip freeze`
- raise an error if `cloudpickle.__version__` doesn't match the version specified in the provided requirements
Previously, we relied on `pip freeze` to get us the `cloudpickle` version that the Client used to serialize the model. Unfortunately, this fails when the user's environment is using pip3 or conda. Fortunately, `cloudpickle` provides a `__version__` attribute that we can use instead!
> 1210: Use cloudpickle.__version__ instead of pip freeze for requirements.txt 

- verta/tests/test_metadata.py
- verta/tests/utils.py
- verta/verta/_utils.py
- verta/verta/client.py
- enable conflict testing for attribute logging
- I disabled this a while back because at the time it wasn't implemented, but it looks like it's there now!
- implement composite `hypothesis` strategies for key-values
- These are not currently being used because `hypothesis` doesn't work well with our integration tests, but I'm putting them in this PR since they were implemented anyway.
- enable converting Python `list`s and `dict`s into protobuf `Value` Messages and vice versa
- Through the Client API, this is only enabled for attributes.
This actually requires **no** backend changes. For logging metadata, the backend currently [passes the inbound Message](https://github.com/VertaAI/verta-backend/blob/development/src/main/java/com/mitdbg/modeldb/experimentRun/ExperimentRunDAOMongoImpl.java …
> 1182: Support logging lists and dictionaries as attributes

- verta/verta/client.py
I had enabled logging collections as attributes in #1182, but this was not enabled on the `attrs` parameter on, say, `client.set_experiment_run()`. This PR fixes that.
Currently, logging attributes directly on Projects and Experiments is completely meaningless (as it's not supported in the UI, nor are `get_attribute()` functions in the Client), but I already supported an `attrs` parameter in their `client.set_*()` functions so I may as well support collections through them.
> Enable logging attrs colles on client.set_*()

- verta/verta/_utils.py
- verta/verta/client.py
- [optionally import Jupyter dependencies `ipykernel` and `IPython`](https://github.com/VertaAI/modeldb-client/pull/117/files#diff-0320d7c96f347d1e665817a9d5a22f98R28)
- [create internal utility function to force-save the current Jupyter notebook (thanks Josh) and return a copy of its contents when the file is rewritten](https://github.com/VertaAI/modeldb-client/pull/117/files#diff-0320d7c96f347d1e665817a9d5a22f98R447)
- [create internal utility function to locate the current Jupyter notebook's filepath](https://github.com/VertaAI/modeldb-client/pull/117/files#diff-0320d7c96f347d1e665817a9d5a22f98R500)
- [create internal utility function to locate the current Python script's filepath](https://github.com/VertaAI/modeldb-client/pull/117/files#diff-0320d7c96f347d1e665817a9d5a22f98R537)
- …
> Implement Code Versioning v0

- verta/tests/conftest.py
- verta/tests/test_protos.py
- verta/tests/utils.py
- verta/verta/_utils.py
- verta/verta/client.py
- add `ignore_conn_err` boolean param/attr to `Client` class
- if `ignore_conn_err`, have `_utils.make_request` return an empty successful response
- create internal utility `Connection` class to track connection configuration settings
- update pytests to use `Connection`
This almost goes without saying, but using the Client to get data from ExperimentRuns may lead to workflow failures because instead of returning valid data, they return default values and empty collections.
Also, because successes are fabricated, various Client print statements will be lies/nonsensical, such as "connection successfully established" and "set existing Project: ". This could be remedied in the future.
> Implement Option to Silence Client Connection Errors

- verta/verta/_utils.py
- verta/verta/client.py
This utility is for basically unpacking directory paths (e.g. `utils/`) into actual filepaths (e.g. `utils/a.py`, `utils/b.py`) which is useful for ZIP archiving.
> Implement find_filepaths() internal utility

- verta/verta/_demo_utils.py
- set access token in request headers
- use `request`'s `json` parameter (instead of `data`), which automatically sets "Content-Type: application/json" in request headers
> Use new prediction endpoint interface

- verta/verta/_utils.py
A wise philosopher once said:
- remove `_utils.to_timestamp()` because we no longer need to convert `datetime.datetime` objects into Unix timestamps
- use `time.time()` instead of `datetime.datetime.now()`
- refuse to parse human-readable datetime strings into Unix timestamps without Pandas installed
- Before, I would fall back to using the `datetime` module for [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) strings, but really no one uses that so it's pointless and not worth the trouble.
The following two runs were logged at 5:32pm.
Before:
After:
> Resolve Daylight Savings Time Timestamp Fiasco

- verta/verta/_artifact_utils.py
- verta/verta/client.py
~**This change has not yet been tested; this draft PR is for reference (or reckless merging).**~
- fix an unrelated bug in `_artifact_utils.serialize_model()`
- fix an unrelated bug in `run.log_model_for_deployment()`
- update Clientside find `message`s because they were [moved from `ExperiementRunService` to `CommonService`](https://github.com/VertaAI/protos-modeldb/pull/29) (unrelated, but required because it's packaged with the protos update)
- obtain and log artifact file extensions
This PR accompanies https://github.com/VertaAI/protos-modeldb/pull/27 and https://github.com/VertaAI/verta-backend/pull/164
> Implement Artifact File Extensions

- verta/verta/_utils.py
- verta/verta/client.py
- implement `ExperimentRun.log_code()` and `ExperimentRun.get_code()`
**This does not currently auto-save the notebook.**
Instead it reads from whatever is on disk (basically the latest checkpoint).
The combination of:
- `zipfile` not allowing writes directly from stream objects
- notebook discovery, saving, and reading introducing some wack race conditions
makes it quite a headache to accommodate notebook auto-saving. I'm thinking about doing it with temp files, but that'll take a while to implement and this feature works reasonably without it.
> Implement log_code() and get_code()

- verta/verta/_utils.py
- verta/verta/client.py
> Code Versioning: Resurrected

- verta/docs/reference/api.rst
- verta/verta/client.py
- create superclass `_ModelDBEntity` with `_get_url_for_artifact()`, `log_code()`, and `get_code()`
- have `Project`, `Experiment`, and `ExperimentRun` subclass `_ModelDBEntity`
This superclass has been a long time coming anyway, and I prefer it (in spite of its awkward subclass typecheck, which is "temporary" ) to copy&pasting the 200 lines of `log_code()` and `get_code()` to `Project` and `Experiment`.
This PR is only for the sake of Code Versioning. I expect more functions to be migrated/implemented in `_ModelDBEntity` down the line.
> Create superclass to share log_code() and get_code()

- verta/verta/client.py
This directly enables proper downloading of file-like Artifacts from the Web App—still without touching Artifact keys.
> Include file extension in upload path

- verta/verta/_utils.py
- verta/verta/client.py
Things to always be printed:
- when an artifact upload is complete
Things to be printed when `debug=True`:
- whether email & dev key were found on `Client.__init__()`
- what email & dev key (first 8 characters) were found
- how many bytes are being uploaded for every logged artifact
- in `log_model_for_deployment()`:
- type of `model`
- contents of `model_api`
- contents of `requirements`
- in `log_modules()`:
- contents of `sys.path`
- contents of `search_paths`
- contents of `custom_modules.zip`
> Add debug flag to Client for printing more verbose info

- verta/verta/_demo_utils.py
Includes changes to `development` from #145 (get rid of input headers, enable custom prediction URLs) because my commit history is a mess.
Successful predictions have been successfully predicted with:
- [modeldb-client/workflows/examples/sklearn.ipynb](https://github.com/VertaAI/modeldb-client/blob/master/workflows/examples/sklearn.ipynb)
- [modeldb-client/workflows/examples/tensorflow.ipynb](https://github.com/VertaAI/modeldb-client/blob/master/workflows/examples/tensorflow.ipynb)
- [modeldb-client/workflows/examples/pytorch.ipynb](https://github.com/VertaAI/modeldb-client/blob/master/workflows/examples/pytorch.ipynb)
- [modeldb-client/workflows/examples/xgboost.ipynb](https://github.com/VertaAI/modeldb-client/blob/master/workflows/examples/xgboost.ipynb)
Retry logic has been tested by …
> Upgrade demo util predict

- verta/verta/client.py
Here is my guess how to handle such case:
- `/v1/project/verifyConnection` could return _401 Unauthorized_ if headers (`Grpc-Metadata-email` and `Grpc-Metadata-developer_key`) contain invalid values. I suppose this endpoint should be modified for this case
- check the status code and raise a proper exception
I think the main point here is to prevent instantiation of `Client` with invalid credentials.
Please, suggest how should I implement this.
> [WIP] #150 Add user-friendly error for authentication failure

- verta/verta/_demo_utils.py
Bad gateway means that an error happened on the backend. This PR
propagates the error message back to the client. For instance:
```
ValueError: Got error message from backend:
Traceback (most recent call last):
File "<ipython-input-81-f864aeb8f6bd>", line 6, in predict
ValueError: Foobar
```
> Raise exception with the backend message in case of a bad gateway

- verta/verta/_artifact_utils.py
- verta/verta/_demo_utils.py
- verta/verta/client.py
Reverts VertaAI/modeldb-client#158
This will be restored once we figure out the design. The backend is backwards compatible, so it shouldn't have to change.
> Revert "Add support for multiple arguments in model"

- verta/verta/_utils.py
- verta/verta/client.py
- `_utils.find_filepaths()` now has a flag `include_venv: bool`
Since a virtual environment directory could be called anything, this technique identifies such directories by looking for a `bin/python` inside.
`run.log_modules()` is taking too long with the virtual environment, so I don't have a screenshot.
This number is completely meaningless without the **Before** image.
> VR-1844: Ignore virtual environment dirs in log_modules()

- verta/verta/_demo_utils.py
The status endpoint returns a message as follows when the deployed model has an error: 
```
{
"status": "error",
"message": "Model killed: out of memory"
}
```
Added a RuntimeError message with the error detail. This a screenshot of the error msg: 
Any suggestions on formatting since this is a bit cluttered?
> Added handling of deployed models with errors

- verta/verta/client.py
- support passing a full URI as `host` in `Client(host)`
- mark `port` in `Client(host, port)` as soon-to-be-deprecated
- Previously, `scheme` would be `"http"` if auth credentials are not provided, and `"https"` if they are. This is still the default, but if a scheme is present in `host` (e.g. `"http://dev.verta.ai/`) then it will be used instead.
This is the logic being used. Note that  `scheme == None` represents using the default mentioned in **Notes**.
> 1776: Support passing a full URI as host in Client(host)

- verta/tests/test_datasets.py
- verta/verta/_dataset.py
- verta/verta/client.py
- unify `client.create_*_dataset()`s into a single `client.create_dataset(type="*")`
- subclass `Dataset` to handle specific Datasets
This is being done to enable `dataset.create_version()`, since e.g. S3 and BigQuery Datasets have different `VersionInfo`s
> VR-2010: Implement Specific Dataset Subclasses

- verta/verta/client.py
- workflows/demos/census-end-to-end-local-data-example.ipynb
- workflows/demos/census-end-to-end-s3-example.ipynb
- workflows/demos/nyc-taxi-atlas-end-to-end.ipynb
This is to be consistent with the existing `set_project()`, `set_experiment()` nomenclature we're using, where `set` means "get if exists, otherwise create".
There's also a little/major bug here that's been logged as VR-2088
> Rename create_dataset() to set_dataset()

- verta/tests/test_datasets.py
- verta/verta/client.py
- remove ability to create `RawDataset` because I've realized that `RawDatasetVersion`s are basically not implemented
- in `ExperimentRun.log_dataset()`:
- raise `ValueError` when trying to log a `Dataset`
- call `log_dataset_version()` when trying to log a `DatasetVersion`
- otherwise, use the artifact logging mechanisms to upload the object
> Ensure run.log_dataset() is still usable 

- verta/verta/_dataset.py
- verta/verta/_demo_utils.py
- verta/verta/client.py
- implement a more helpful `DatasetVersion.__repr__()`
- remove a stray letter in a docstring
- remove unused `ExperimentRun._log_artifact_path(…, linked_artifact_id)`
- support getting old artifact- and path-based datasets
Behold, the power of backwards compatibility:
> Various patches

- verta/tests/conftest.py
- verta/tests/test_artifacts.py
- verta/tests/test_backend.py
- verta/tests/test_datasets.py
- set actual values for default S3 and GCS so errors are more interpretable
- make the `output_path` fixture actually resistant to race conditions
- comment out defunct Dataset Versioning tests
- reinstate adequate Dataset Versioning tests
- make Dataset Versioning tests more generalizable
> Fix up DataVer tests

- verta/verta/_dataset.py
Python 2 doesn't allow passing in explicit keyword arguments after `**kwargs`, apparently.
> Shift arg order for Py2

- verta/verta/client.py
Before, `get_metric(key)`, `get_hyperparameter(key)`, etc. would call the `getMetrics` RPC,
and then attempt a `.get(key)` on a dictionary representation of that response.
If the result of the `.get(key)` is `None`, then the Client would raise a `KeyError`.
This is problematic because if the user genuinely logs `None` as the value, `get_metric()` would result in a false negative. This PR fixes that.
This unblocks tests I have which verify that `None` can be logged as values.
The WebApp currently displays `null` values as `0`, but the Client has always supported logging `None` as a value so at the very least, it will support getting those `None`s back.
> Support gets when val is None

- verta/verta/client.py
These deprecations have been on my to-do list for a while.
- mark `client.expt_runs` as deprecated
- This is because its intention is ambiguous: is it the Runs under a Project, or under an Experiment? `proj.expt_runs` and `expt.expt_runs` are preferred.
- mark `expt_runs.find(…, ret_all_info)` as deprecated
- It returns protobuf `Message` objects which are unintuitive and actually borderline unusable, and I'm pretty sure absolutely no one is using it. It was originally only implemented because there was no easy way to view an `ExperimentRun` information, but now we have `ExperimentRun.__repr__()`.
> Mark deprecations

- verta/verta/_dataset.py
- verta/verta/_demo_utils.py
- verta/verta/_utils.py
- verta/verta/client.py
Before, the Client would naïvely call `raise_for_status()` on `requests::Response`s, which masks any error messages provided by the back end—and instead gives a generic explanation of the HTTP error code.
This new utility checks the `Response` for an error message from the backend and propagates it if present—otherwise, it will continue using the default as before.
- implement `_utils::raise_for_http_error()`
- replace every `response.raise_for_status()` in the package with `utils.raise_for_http_error(response)`
These are just examples of the utility function—the actual `Client` error message for key conflicts is much more user-friendly I promise.
**Before, using the default HTTP error message from `requests`:**
**After, using the back end error message:**
> VR-2111: Propagate the error messages generated by the back end

- verta/verta/client.py
Perform basic validation for Clientside querying keys because the back end currently does nothing.
This isn't meant to be exhaustive or permanent, but at the very least it catches typos on the user's end.
Then again, it doesn't point the user towards valid keys they can try, but I already wrote this so it's now a PR.
> Validate keys for Clientside querying

- verta/verta/client.py
#194 accidentally forbids dot-delimited keys like `"metrics.accuracy"`.
> Allow dot-delimited keys

- verta/tests/conftest.py
- verta/tests/test_artifacts.py
- add fixture to access `conftest.py`'s `RANDOM_SEED`
- add positive functionality tests for logging `sklearn`, `torch`, `keras`, functions, and custom models
The following conceivable tests are not implemented:
- logging `xgboost`
- rejecting pure, non-`keras` `tensorflow`
> VR-2119: Implement model logging tests

- verta/tests/test_entities.py
- verta/tests/test_query.py
I've reached a point where I believe the time it's taking to implement these tests is greater than the actual present value of this feature (I don't think anyone's relying on this functionality right now).
- revamp `verta::client::ExperimentRuns` magic method tests
- revamp tests for `find`, `sort`, `top_k`, and `bottom_k` for metrics and hyperparameters
- implement tests for `find` by ExperimentRun `id`, `experiment_id`, and `project_id`
- implement test for `find` by tags
The following tests have *not* been implemented
- validation of dot-delimited keys e.g. `find` by `"metrics.acc"` allowed, but `find` by `"metrics"` not due to a lack of a metric key
- querying for attributes
- tricky because attribute values can be collections
- querying for `created_time`, etc.
- I doubt anyone is …
> VR-2113: Implement Clientside Querying Tests

- verta/verta/client.py
The superclass for `Project`, `Experiment`, and `ExperimentRun` stores a protocol buffer module directly as an attribute, so it can't be `pickle`d.
This has caused problems for end-to-end tests that involve `multiprocessing`, which uses `pickle` (and not `cloudpickle`).
This fixes that.
> Fix a bug where verta objects couldn't be pickled

- verta/verta/client.py
This wasn't in the current sprint, but it was getting a bit annoying while testing code versioning.
- copy logic from `_log_artifact()` to `log_code()` to log file extension in `path`
> VR-1913: Log code ver artifact path with .zip

- verta/verta/client.py
I've discovered that passing CSV-like strings into `pickle.loads()` can somehow result in `KeyError`s and `ValueError`s. Thanks, Python.
> Catch other unpickling errors

- verta/tests/conftest.py
- verta/tests/test_log_code.py
- verta/tests/utils.py
These tests cover:
- successfully logging git in a repository
- rejecting logging git when not in a reposity
- successfully logging a `.py` source file
These tests do not cover:
- successfully logging a `.ipynb` source file because I can't run pytest inside a running Jupyter Notebook
- successfully logging a Google Colab notebook source file because I can't run pytest inside a Colab instance
> VR-2117: Implement log_code() tests

- verta/verta/client.py
I was hoping to avoid this, but then I got a `ModuleNotFound` error from unpickling a CSV string, so it looks like it can genuinely throw anything.
> Catch all errors from unpickling

- verta/verta/client.py
A bit controversial here, but since we decided to make `use_git` a Client-level option, mutating it during a workflow has awkward consequences (e.g. the Project has a git code version, but then the Experiment can have an artifact code version).
This could easily be confusing and I'd like to discourage it.
Also note that before this change, mutating `use_git` was completely unsupported, so `client.use_git = True` would "succeed" but have absolutely no effect.
> Prevent mutating client.use_git

- verta/docs/reference/api/deployment.rst
- verta/verta/deployment.py
This is for the new public `verta::deployment::DeployedModel`.
`model_id` makes no sense; `run_id` is more in line with Client terminology.
> Rename model_id param to run_id

- verta/tests/conftest.py
- verta/tests/modelapi_hypothesis/api_generator.py
- verta/tests/test_artifacts.py
- verta/tests/test_backend.py
- verta/tests/test_datasets.py
- verta/tests/test_deployment.py
- verta/tests/test_log_code.py
- verta/tests/test_query.py
- verta/verta/utils.py
Only Client change is that `ModelAPI` generates `VertaJson` by sorting the `'name'`s
> Get tests in a passable state

- verta/verta/monitoring.py
- `HistogramProcessor` logic has been moved entirely to `FloatHistogramProcessor`
- `bin_boundaries` and `reference_counts` are now tracked solely in the `Processor`'s `config`.
- `reduce_states()` and `get_from_state()` are commented out for now.
- `BinaryHistogramProcessor` now takes a much more categorical approach.
> VR-2301: Remove bin_boundaries and reference_counts from state

- verta/verta/monitoring.py
Processors now simply return unchanged `state` when:
- the key is missing
- the value is `None`
An `IndexError` would still be raised, because it suggests a malformed input. A proper list with missing data should be the correct length, but with `None`s for missing values!
> Handle Missing Data

- verta/verta/client.py
- verta/verta/monitoring.py
Sometimes, `data` might just be a scalar, rather than a list of values. 
- make `feature_name` optional in `Processor`s
- in `log_model_for_deployment()`, if modelAPI says output is not list or dict, then set name and index to `None` to signal that `Processor` should expect a scalar
> Handle Scalar Data in Processors

- verta/verta/monitoring.py
- `__init__()` takes a _proportion_ (<=1) for reference. This is to make sure the user gives it the correct value.
- If I allowed >1, then there's no way to check if the user is entering the proportion or accidentally the percentage. Only allowing <=1 means I can enforce that only the proportion is possible.
- This number is converted to a <=100 percentage on `get_from_state()`.
> VR-2332: Implement Missing Data Processors

- verta/verta/monitoring.py
In accordance with [VR-2331](https://vertaai.atlassian.net/browse/VR-2331)'s description, and because using `-1` as a special value for _arbitrary floats_ is problematic!!
> [on hold] Remove [-1] limits from _FloatHistogramProcessor.get_from_state()

- verta/tests/test_artifacts.py
- verta/tests/test_deployment.py
- verta/verta/_artifact_utils.py
TensorFlow v1.15 was released yesterday, which rejects bytestreams for saving/loading Keras models and instead now only accepts filenames as arguments.
This issue may sound familiar—it was also present in older versions of TensorFlow and H5py.
For Keras (de)serialization, I use a `NamedTemporaryFile` instead of a `BytesIO`.
Left is Python 3 & TensorFlow==1.15
Right is Python 2 & TensorFlow==1.13
> VR-2496: Use NamedTemporaryFiles to handle (de)serializing Keras

- verta/tests/conftest.py
- verta/tests/test_datasets.py
- verta/tests/utils.py
- Datasets created during a test can be tracked by appending them to a fixture
- Datasets tracked by that fixture are deleted when a test ends
- use of the fixture is a little bit hacky—easy to forget when writing new tests
- deletes datasets even on failed tests so we can't check what happened, though they could be reproduced
> VR-2714: Delete Datasets after tests

- verta/tests/conftest.py
- verta/tests/modelapi_hypothesis/test_modelapi.py
- verta/tests/modelapi_hypothesis/test_value_generator.py
- verta/tests/test_artifacts.py
- verta/tests/test_datasets.py
- verta/tests/test_deployment.py
- verta/tests/test_query.py
I'd like to run comprehensive Client tests to verify that `verta` works without `grpcio`.
Some third-party scientific package used during pytests—not sure which—has `grpcio` as a dependency.
I drew this conclusion from [this Jenkins job](https://jenkins.dev.verta.ai/job/client/job/run-pytest/242/consoleFull) that removed `grpcio` as a Client dependency, but it still installed it anyway.
Tests and imports/configurations need to be decoupled slightly, so that "basic" pytests can be run even if third-party packages are not available.
- move third-party package imports and fixtures to the test scripts that use them
- skip those test scripts if those packages are not installed
- replace `np.random` in `conftest.py` with the stdlib `random`
> Decouple test configuration

- verta/tests/test_artifacts.py
- verta/tests/test_datasets.py
- verta/tests/test_deployment.py
Enables simple data versioning and artifact tests to run without unnecessary third-party libraries.
> Shift import checks further into test functions

- verta/tests/test_datasets.py
Based on [this Jenkins run](https://jenkins.dev.verta.ai/job/client/job/run-pytest/285/console), two Jenkins jobs running simultaneously ended up using the same Dataset names (randomly generated from a util), and encountered a race condition on creation and cleanup.
I believe this is because the tests uses the same random seed, so name collisions are certainly likely.
This PR switches from the random name generation to `Dataset`'s default name generation, which is based on time, and *does not decisively fix the problem*, but should be less collision-prone.
Long term solutions include:
- fixing the impl of `._create()`s so we can handle collisions properly instead of this opaque "try to create otherwise get" behavior
- getting rid of names entirely
> Let datasets generate their own names

- verta/docs/reference/api/experimentrun.rst
- verta/tests/test_deployment.py
- verta/verta/_artifact_utils.py
- verta/verta/client.py
Top example reads [one of the repo's `requirements.txt`s](https://github.com/VertaAI/modeldb-client/blob/a5e042e/workflows/requirements.txt) and fills in version pins.
Bottom example takes module names and fills in version pins. Note:
- `>=999.13.10` is ignored and replaced with the environment's version, which is lower
- translation of `'sklearn'` to `'scikit-learn'`
- injections of `verta` and `cloudpickle`
> Implement log_requirements()

- verta/tests/test_deployment.py
- verta/verta/_artifact_utils.py
Predictions are successful, trust me.
The class was:
```python
class Model:
def __init__(self, artifacts=None):
print("We're in business")
def predict(self, data):
return [0]
```
`model.pkl` is a serialized class:
This uses the [in-progress `ClassModelWrapper`](https://github.com/VertaAI/DeploymentService/pull/179/files), and the new model type `"class"`:
> VR-2868: Support logging class as model

- verta/tests/conftest.py
- verta/tests/test_artifacts.py
- verta/tests/test_deployment.py
- verta/verta/client.py
As an example, this unzips `banana.zip` into `cache/artifacts/$RUN_ID/banana/`.
I am confident this is fine because the Client has never allowed logging artifacts with keys that contain periods, i.e. a user in normal usage cannot log both `"banana"` and `"banana.zip"` (because they can only log one artifact with the key `"banana"`, and the `'.zip'` is appended internally by the Client), so there will not be a collision in the cache.
> VR-2925: Unzip ZIPs in fetch_artifacts()

- verta/tests/test_utils.py
- verta/verta/_utils.py
- verta/verta/deployment.py
I chose to do the type/class checks by string comparison because the method used [in Model Service](https://github.com/VertaAI/DeploymentService/blob/5641633/model_service/app/api/predict_resource.py#L20) (attempting imports of the library, since the Client tries to not enforce hard dependencies) would introduce many, many more lines of code and in my opinion add complexity.
String comparisons can be prone to typos, but that's why I have tests.
> VR-2875: Convert common external datatypes into JSON

- verta/setup.py
- verta/verta/_artifact_utils.py
- verta/verta/_dataset.py
- verta/verta/_six.py
- verta/verta/_utils.py
- verta/verta/client.py
- verta/verta/deployment.py
- verta/verta/utils.py
[`pytest`s succeed](https://jenkins.dev.verta.ai/job/client/job/test-python-versions/132/console). Note that `six` is still installed because `pathlib2` and `protobuf` (`six>=1.9`) depend on it.
Also our test suite itself still uses it, but it's purged from the Client library source:
> Include internal copy of six v1.12.0

- verta/tests/test_artifacts.py
- verta/verta/_utils.py
- verta/verta/client.py
This implementation is very concerning because it's a delete-then-write, where the write involves a ModelDB step and an Artifact Store step. This means that many things could potentially go wrong before the operation is complete, and leave the artifact in a bad state.
This would be **much** better if ModelDB backend handled the overwrite internally in a way that fails safely.
`log_artifact()`
`log_model()`
`log_requirements()`
`log_training_data()`
`log_setup_script()`
`log_code()`
`log_dataset_version()`
> VR-2902: Add overwrite parameter to artifact logging functions

- verta/verta/client.py
Python 2 has a `unicode` string type, but Clientside `find()` currently explicitly handles `str`.
> VR-3009: Properly handle Python 2 string types in Clientside find

- verta/tests/test_deployment.py
Two weeks ago, I introduced [a bug](https://github.com/VertaAI/modeldb-client/pull/320) where error messages from deployment weren't being propagated. It wasn't caught by tests because this test didn't check the content of the error message; now it does.
> VR-3036: Check for presence of error msg

- verta/verta/_utils.py
- verta/verta/client.py
Filtering out [real] virtual environment files involves two steps:
1. remove `possible-venv/lib/python*/site-packages` from `sys.path`'s elements if `possible-venv/bin/python*` exists
1. while walking through directories for files to upload, ignore inner `possible-venv/` we might find if `possible-venv/bin/python*` exists
> VR-3016: fix _log_modules() to include fake venvs

- verta/verta/deployment.py
To avoid confusion when the user doesn't pass in `token` because it's optional in the method signature.
> VR-2956: Require token in from_url(), even if None

- verta/verta/_utils.py
- verta/verta/client.py
`TernaryEnum` was moved from `public::modeldb::CommonService` to `public::common::CommonService`.
My linter caught this, but I neglected to check it before #332 because I thought my tests would catch any problems.
My tests did _not_ catch this because `TernaryEnum` is only used when logging a Git code version on a dirty commit, which is not covered in my tests because I hadn't figured a way to manipulate the Git working tree in the test containers.
> Fix Client bug from protos movement

- verta/verta/_utils.py
- verta/verta/integrations/keras/__init__.py
- verta/verta/integrations/tensorflow/__init__.py
- verta/verta/integrations/xgboost/__init__.py
In the spirit of stronger framework integration and a smoother user experience: `log_metric()`, `log_hyperparameter()`, etc. will coerce arguments to built-in Python types.
Before, logging `np.array(3)` or `torch.tensor(3)` would result in a `TypeError`.  
Now, a user in PyTorch can type
```python
run.log_metric("loss", loss)
```
instead of
```python
run.log_metric("loss", loss.tolist())
```
> Try to coerce values to built-ins for logging non-artifacts

- verta/docs/reference/api/integrations.rst
- verta/tests/test_integrations.py
- verta/verta/integrations/torch/__init__.py
This hook only logs information about the network's submodules, for example:
```python
{
'layer_0_name': 'Linear',
'layer_0_in_features': 3,
'layer_0_out_features': 512,
'layer_1_name': 'Dropout',
'layer_1_p': 0.2,
'layer_1_inplace': False,
'layer_2_name': 'Linear',
'layer_2_in_features': 512,
'layer_2_out_features': 10,
}
```
Unfortunately because of how PyTorch works, `loss` is not exposed to hooks. Weights and gradients are, though, if we ever want to do something with those.
> VR-3161: Implement hook for PyTorch
